name: erection_test
description: "Erection Test App is based on the IIEF-15 Questionnaire that provides subjective evaluation for different aspects of male sexual function."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # cupertino_icons: ^1.0.8  
  equatable: ^2.0.5
  provider: ^6.1.2
  go_router: ^17.0.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/fonts/IBM/
    - assets/lang/
    - assets/json/


  fonts:
    - family: IBM
      fonts:
        - asset: assets/fonts/IBM/font-Thin-100.ttf
          style: normal
          weight: 100
        - asset: assets/fonts/IBM/font-ExtraLight-200.ttf
          style: normal
          weight: 200
        - asset: assets/fonts/IBM/font-Light-300.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/IBM/font-Regular-400.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/IBM/font-Medium-500.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/IBM/font-SemiBold-600.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/IBM/font-Bold-700.ttf
          style: normal
          weight: 700